### PR TITLE
a minor edit of the DataSourceFactoryManager and a skeleton of an …

### PR DESCRIPTION
**Pull request by alexanderkjall**
PGDataSourceFactory implementation.

This moves the NullPointerException in PGDataSourceTest.builder() from .builder() to ds.getConnection().

After this I hope it's possible to start writing some more interesting code, it took a lot of time to debug why DataSourceFactoryManager was broken.

### CODE REVIEW

**Comment by davecramer** [comment]
I've added you as a collaborator, no need to wait for me to merge

**Comment by alexanderkjall** [comment]
Thanks, I'll try to signal when there is code that I want to talk about,
it's extremly useful to have someone else to talk to about how stuff should
work.

2018-03-19 20:35 GMT+01:00 Dave Cramer <notifications@github.com>:

**Comment by davecramer** [comment]
Sounds good!

**Comment by davecramer** [comment]
BTW, my thoughts on this were to just hack something together that worked for testing as ultimately the final code will come from upstream

**Comment by davecramer** [comment]
jdbc 10 http://jdk.java.net/10/

**Comment by alexanderkjall** [comment]
Looks like we need to bump the number in README.md to 11

**Pull request merged**
